version: '3.4'
services:
  db:
    container_name: skincare_pg_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
    volumes:
      - skincare_db:/var/lib/postgresql/data
    networks:
      - back-tier
  skinshareapp:
    image: skinshare
    depends_on: 
      - db
    build:
      context: Skinshare.Web
      dockerfile: Dockerfile
    ports:
      - 5000:80
    volumes:
      - $HOME/.aws:/root/.aws
    networks:
      - back-tier

volumes:
  skincare_db: {}

networks:
  back-tier:
