version: '3.1'
services:
  db:
    container_name: skincare_pg_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
    volumes:
      - skincare_db:/var/lib/postgresql/data

volumes:
  skincare_db:
